const API_URI = "https://the-trivia-api.com/v2/questions";
const POPULATE = "populate";
const INDEX_INCREMENT = "INDEX_INCREMENT";
const GET_CURRENT_QUESTION = "GET_CURRENT_QUESTION";
const SHUFFLE_ANSWER = "SHUFFLE_ANSWER";
const RESTART_GAME = "RESTART_GAME";
const TIMEOUT = "TIMEOUT";
const POINTS_ON_CORRECT = 15;
const FETCH_OPTIONS = {};
const DELAY = 5;
const TIME_LIMIT_MINUTES = 10;
const TIME_LIMIT_SECONDS = 0;

export {
  API_URI,
  POPULATE,
  GET_CURRENT_QUESTION,
  RESTART_GAME,
  TIMEOUT,
  INDEX_INCREMENT,
  SHUFFLE_ANSWER,
  POINTS_ON_CORRECT,
  FETCH_OPTIONS,
  DELAY,
  TIME_LIMIT_MINUTES,
  TIME_LIMIT_SECONDS,
};
